anypoint:
  platform:
    protocol: "HTTPS"
    host: "anypoint.mulesoft.com"
    basepath: ""
    port: "443"
    timeout: "60000"
    organizationId: 
    ignoredBusinessGroups: 
    clientId: 
    clientSecret: 
  auditLogs:
    limitRecords: "150" #pagination limit records extraction
    
scheduler:
  frequency: 
    cron: "0 */10 * ? * *" 
    #Sample for dev "0 17 * * * ? *" At second :00 of minute :17 of every hour
    #Sample for prod "0 0 0 * * ? *" At 00:00:00am every day
    #https://www.freeformatter.com/cron-expression-generator-quartz.html
    timezone: "GMT-5"
  startTime: "2021-09-15T01:00:00.000Z[UTC]"

splunk:
  hec:
    protocol: "HTTPS"
    host: # ".splunkcloud.com"
    port: # "8088"
    basepath: "/services/collector"
    token: 
    channel: 
  index: 
  sourcetype: "_json"
  source: "mule"
  
object-store:
  token:
    ttl: "5"
    interval: "1"
  watermark:
    ttl: "4320" # 72 Hours = 60 * 72
    interval: "5" # 5 Minutes
schedule:
  default-time-period: "PT12H" # "PT12H" # Hours before current DateTime to retrieve if Last query is not present